---
- hosts: webservers 
  become: True
  tasks:
    - name: Install packages
      yum:
        name: "nginx"
        state: "present"

    - name: Start Nginx server
      service:
        name: nginx
        state: started
        enabled: True

    - name: Deploy static website
      copy:
        src: index.html
        dest: /usr/share/nginx/html

#   - name: Modify the nginx configuration
#     copy:
#       src: local destination path
#       dest: /etc/nginx/nginx.conf
